#:kivy 2.1.0

Screens:

<Screens>:
    current: "MainMenu"
    MainMenu:
    SettingsMenu:

<MainMenu>:
    name: "MainMenu"
    BoxLayout:
        orientation: 'vertical'
        Button:
            text: "Tracker Logo"
            pos_hint: {'center_x': 0.5}
        BoxLayout:
            size_hint: 1, 0.5
            spacing: "20dp"
            padding: "20dp"
            Button:
                text: "Einstellungen"
                on_press: root.manager.current = "SettingsMenu"
            Button:
                text: "Start Server"
                on_press: root.launchserver()
            Button:
                text: "Starte Emulator"
                on_press: root.launchbh()

<SettingsMenu>:
    name: "SettingsMenu"
    GridLayout:
        rows: 2
        BoxLayout:
            orientation: "horizontal"
            size_hint: 1, 0.15
            pos_hint: {"top": 0}
            ToggleButton:
                group: "settings"
                text: "Sprite\nPfade"
                on_press: root.changesettingscreen('sprite')
                allow_no_selection: False
            ToggleButton:
                group: "settings"
                text: "Bizhawk"
                on_press: root.changesettingscreen('bizhawk')
                allow_no_selection: False
            ToggleButton:
                group: "settings"
                text: "OBS"
                on_press: root.changesettingscreen('obs')
                allow_no_selection: False
            ToggleButton:
                group: "settings"
                text: "Remote"
                on_press: root.changesettingscreen('remote')
                allow_no_selection: False
            ToggleButton:
                group: "settings"
                text: "Spieler"
                on_press: root.changesettingscreen('player')
                allow_no_selection: False
            Button:
                text: "Hauptmenü"
                on_press: root.manager.current = "MainMenu"
        Screen:

<SpriteSettings>:
    GridLayout:
        cols: 2
        Label:
            text: 'Speicherort'
            size_hint: .2, 1
        AnchorLayout:
            anchor_x: 'left'
            TextInput:
                id: common_path
                size_hint: 1, None
                size: "20dp", "30dp"
                multiline: False
                write_tab: False
                on_text_validate: root.save_changes()
        Label:
            text: 'animierte\nSprites?'
            size_hint: .2, 1
        BoxLayout:
            orientation: 'horizontal'
            AnchorLayout:
                anchor_x: 'left'
                size_hint: .1, 1
                CheckBox:
                    id: animated_check
                    size_hint: None, None
                    size: "20dp", "20dp"
                    on_press: root.save_changes()
            Label:
                size_hint: 1, 1
                text: 'Sprites jedes\nSpiels einzeln\nfestlegen?'
            AnchorLayout:
                anchor_x: 'left'
                size_hint: .1, 1
                CheckBox:
                    id: game_sprites_check
                    size_hint: None, None
                    size: "20dp", "20dp"
                    on_press: root.sprite_paths_setting()
            AnchorLayout:
                anchor_x: 'center'
                size_hint: .8, 1
                Button:
                    id: game_sprites
                    text: 'Spritepfade der\neinzelnen Games'
                    size_hint: 1, .5
                    on_press: root.parent.parent.changesettingscreen('games')
        Label:
            text: 'Sortierung'
            size_hint: .2, 1
        BoxLayout:
            id: sortierung
            orientation: "horizontal"
            spacing: "20dp"
            padding: "5dp", 0
            ToggleButton:
                size_hint: 1, .5
                pos_hint: {"center_y": .5}
                on_press: root.save_changes()
                text: 'DexNr.'
                group:"sort"
                allow_no_selection: False
            ToggleButton:
                size_hint: 1, .5
                pos_hint: {"center_y": .5}
                on_press: root.save_changes()
                text: 'Team'
                group:"sort"
                allow_no_selection: False
            ToggleButton:
                size_hint: 1, .5
                pos_hint: {"center_y": .5}
                on_press: root.save_changes()
                text: 'Level'
                group:"sort"
                allow_no_selection: False
            ToggleButton:
                size_hint: 1, .5
                pos_hint: {"center_y": .5}
                on_press: root.save_changes()
                text: 'Route'
                group:"sort"
                allow_no_selection: False

<SpritesGames>:
    GridLayout:
        cols: 2
        Label:
            text: "rot/blau"
            size_hint: .4, 1
        AnchorLayout:
            anchor_x: 'left'
            TextInput:
                id: gen1_red
                size_hint: 1, None
                size: "20dp", "30dp"
                multiline: False
                write_tab: False
                on_text_validate: root.save_changes()
        Label:
            text: "gelb"
            size_hint: .4, 1
        AnchorLayout:
            anchor_x: 'left'
            TextInput:
                id: gen1_yellow
                size_hint: 1, None
                size: "20dp", "30dp"
                multiline: False
                write_tab: False
                on_text_validate: root.save_changes()
        Label:
            text: "silber"
            size_hint: .4, 1
        AnchorLayout:
            anchor_x: 'left'
            TextInput:
                id: gen2_silver
                size_hint: 1, None
                size: "20dp", "30dp"
                multiline: False
                write_tab: False
                on_text_validate: root.save_changes()
        Label:
            text: "gold"
            size_hint: .4, 1
        AnchorLayout:
            anchor_x: 'left'
            TextInput:
                id: gen2_gold
                size_hint: 1, None
                size: "20dp", "30dp"
                multiline: False
                write_tab: False
                on_text_validate: root.save_changes()
        Label:
            text: "kristall"
            size_hint: .4, 1
        AnchorLayout:
            anchor_x: 'left'
            TextInput:
                id: gen2_crystal
                size_hint: 1, None
                size: "20dp", "30dp"
                multiline: False
                write_tab: False
                on_text_validate: root.save_changes()
        Label:
            text: "rubin/saphir"
            size_hint: .4, 1
        AnchorLayout:
            anchor_x: 'left'
            TextInput:
                id: gen3_ruby
                size_hint: 1, None
                size: "20dp", "30dp"
                multiline: False
                write_tab: False
                on_text_validate: root.save_changes()
        Label:
            text: "smaragd"
            size_hint: .4, 1
        AnchorLayout:
            anchor_x: 'left'
            TextInput:
                id: gen3_emerald
                size_hint: 1, None
                size: "20dp", "30dp"
                multiline: False
                write_tab: False
                on_text_validate: root.save_changes()
        Label:
            text: "feuerrot/blattgrün"
            size_hint: .4, 1
        AnchorLayout:
            anchor_x: 'left'
            TextInput:
                id: gen3_firered
                size_hint: 1, None
                size: "20dp", "30dp"
                multiline: False
                write_tab: False
                on_text_validate: root.save_changes()
        Label:
            text: "diamant/perl"
            size_hint: .4, 1
        AnchorLayout:
            anchor_x: 'left'
            TextInput:
                id: gen4_diamond
                size_hint: 1, None
                size: "20dp", "30dp"
                multiline: False
                write_tab: False
                on_text_validate: root.save_changes()
        Label:
            text: "platin"
            size_hint: .4, 1
        AnchorLayout:
            anchor_x: 'left'
            TextInput:
                id: gen4_platinum
                size_hint: 1, None
                size: "20dp", "30dp"
                multiline: False
                write_tab: False
                on_text_validate: root.save_changes()
        Label:
            text: "herzgold/seelensilber"
            size_hint: .4, 1
        AnchorLayout:
            anchor_x: 'left'
            TextInput:
                id: gen4_heartgold
                size_hint: 1, None
                size: "20dp", "30dp"
                multiline: False
                write_tab: False
                on_text_validate: root.save_changes()
        Label:
            text: "schwarz/weiß (s2/w2)"
            size_hint: .4, 1
        AnchorLayout:
            anchor_x: 'left'
            TextInput:
                id: gen5_black
                size_hint: 1, None
                size: "20dp", "30dp"
                multiline: False
                write_tab: False
                on_text_validate: root.save_changes()
        Label:
            size_hint: .4, 1
        Button:
            text: "Zurück"
            size_hint: .75, 1
            on_press: root.parent.parent.changesettingscreen('sprite')

<BizhawkSettings>:
    GridLayout:
        cols: 2
        Label:
            text: 'Pfad der\nEmuHawk.exe'
            size_hint: .2, 1
        AnchorLayout:
            anchor_x: 'left'
            TextInput:
                id: bizhawk_exe
                size_hint: 1, None
                size: "20dp", "30dp"
                multiline: False
                write_tab: False
                on_text_validate: root.save_changes()
        Label:
            text: 'IP-Adresse'
            size_hint: .2, 1
        AnchorLayout:
            anchor_x: 'left'
            TextInput:
                id: bizhawk_host
                size_hint: 1, None
                size: "20dp", "30dp"
                multiline: False
                write_tab: False
                on_text_validate: root.save_changes()
        Label:
            text: 'Port'
            size_hint: .2, 1
        AnchorLayout:
            anchor_x: 'left'
            TextInput:
                id: bizhawk_port
                size_hint: 1, None
                size: "20dp", "30dp"
                multiline: False
                write_tab: False
                on_text_validate: root.save_changes()

<OBSSettings>:
    GridLayout:
        id: obs_settings
        cols: 2

<RemoteSettings>:
    GridLayout:
        id: remote_settings
        cols: 2

<PlayerSettings>:
    GridLayout:
        cols: 2
        Label:
            text: 'Anzahl Spieler'
        BoxLayout:
            orientation: 'horizontal'
            CheckBox:
                id: player_count_1
                group: 'player_count'
                pos_hint: {"center_y": .5}
                size_hint: None, None
                size: "20dp", "20dp"
                on_press: root.changeScreen(1)
            Label:
                text: "1"
                pos_hint: {"center_y": .5}
                size_hint: None, None
                size: "20dp", "20dp"
            CheckBox:
                id: player_count_2
                group: 'player_count'
                pos_hint: {"center_y": .5}
                size_hint: None, None
                size: "20dp", "20dp"
                on_press: root.changeScreen(2)
            Label:
                text: "2"
                pos_hint: {"center_y": .5}
                size_hint: None, None
                size: "20dp", "20dp"
            CheckBox:
                id: player_count_3
                group: 'player_count'
                pos_hint: {"center_y": .5}
                size_hint: None, None
                size: "20dp", "20dp"
                on_press: root.changeScreen(3)
            Label:
                text: "3"
                pos_hint: {"center_y": .5}
                size_hint: None, None
                size: "20dp", "20dp"
            CheckBox:
                id: player_count_4
                group: 'player_count'
                pos_hint: {"center_y": .5}
                size_hint: None, None
                size: "20dp", "20dp"
                on_press: root.changeScreen(4)
            Label:
                text: "4"
                pos_hint: {"center_y": .5}
                size_hint: None, None
                size: "20dp", "20dp"
